version: '3.8'

services:
  recipe-manager:
    image: lukemartinlogan/recipe-manager:latest
    ports:
      - "80:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist SQLite database
      - recipe_data_prod:/app/data
      # Persist uploaded images
      - recipe_images_prod:/app/public/images
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - recipe-manager
    restart: always
    profiles:
      - with-nginx

volumes:
  recipe_data_prod:
    driver: local
  recipe_images_prod:
    driver: local