version: '3.8'

services:
  recipe-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist SQLite database
      - recipe_data:/app/data
      # Persist uploaded images (if any)
      - recipe_images:/app/public/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  recipe_data:
    driver: local
  recipe_images:
    driver: local